[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"

solc_version = "0.8.20"
evm_version = "shanghai"

optimizer = true
optimizer_runs = 200

via_ir = false

gas_reports = ["*"]
gas_reports_ignore = []

# Test configuration
fuzz = { runs = 256 }
invariant = { runs = 256, depth = 15 }

# Formatter
fmt = { line_length = 100, tab_width = 4, bracket_spacing = true }

# Documentation
doc = { out = "docs", book = "book.toml", repository = "https://github.com/kelpejol/on-chain-action-guard" }

# Permissions
fs_permissions = [{ access = "read", path = "./"}]
